### ISSUE TITLE
Bot sends the command too fast

### ISSUE THREAD

**Issue by SashoStoichkov** [rolaca11/twitch-cp-title#1]
Heya,

Today on stream I used your plugin for one RPG. It is working too good, that it spoils for the chat when I get the CP because of stream delay.

I suggest adding a little delay (5-10 secs) to the line that sends the command to Twitch chat.

Thanks :)

**Comment by rolaca11** [comment]
Hey, I made some changes, but before I publish it, I'd appreciate it if you could help me with testing. Unfortunately, I'm using a Linux OS and the TwitchBase plugin crashes my game, so I can't do a proper test.

**Comment by rolaca11** [comment]
https://github.com/rolaca11/twitch-cp-title/blob/archives/twitch-cp-title.op here is the unreleased update. You need to set Openplanet to Developer mode and copy the linked file to your `C:\Users\<your username>\OpenplanetNext\Plugins` folder

**Comment by SashoStoichkov** [comment]
I can confirm that the delay works 👍🏻 Also good addition of not hard-coding the amount of secs 👍🏻

**Comment by rolaca11** [comment]
FYI, I uploaded the new version to Openplanet, and waiting for approval. In the meantime, you can use the dev version you tested with, hopefully the approval process won't take long
